### ISSUE TITLE
error when getting event detail for a calendar event

### ISSUE THREAD

**Issue by saschaben** [ilios/calendar#1] opened 2015-10-02 16:32 UTC
when accessing a calendar event detail which is from the "all" event category (i.e. one the user is NOT associated with), we are throwing an error which makes the page fail to load:

`Uncaught TypeError: Cannot read property 'totalLevels' of undefined`

**Comment by saschaben** [comment] 2015-10-02 16:37
also throws the following 404:
![dayview](https://cloud.githubusercontent.com/assets/1753431/10251947/271aea22-68e9-11e5-9c35-8d0a7f34821a.png)

**Comment by jrjohnson** [comment] 2015-10-02 16:50
If anyone gets to this before me I think the issue is in the school events service not correctly parsing the slug to get the right event `to` time from the API.

**Comment by dartajax** [comment] 2015-11-30 23:10
This seems to have been fixed.  I am closing it.  Tests passed.

**Closed by dartajax** 2015-11-30 23:10 UTC
Labels: bug
